// app/routes/admin/components/settings/CertificateSettings.tsx

import { Award } from "lucide-react";
import { useState } from "react";

import { adminData } from "../../data/adminData";
import {
  SettingToggle,
  SettingsCard,
  SettingsPage,
} from "./SettingsPrimitives";

export function CertificateSettings() {
  const data = adminData.settings.certificates;

  const [enabled, setEnabled] = useState(data.enabled);

  const [autoIssue, setAutoIssue] = useState(data.autoIssue);

  const [requireCompletion, setRequireCompletion] = useState(
    data.requireCompletion,
  );

  const [includeInstructor, setIncludeInstructor] = useState(
    data.includeInstructor,
  );

  const [includeId, setIncludeId] = useState(data.includeCertificateId);

  return (
    <SettingsPage
      title="Certificate Settings"
      description="Configure certificate generation and completion requirements."
    >
      <SettingsCard
        title="Certificate Configuration"
        description="Control how certificates are issued to students."
      >
        <div className="space-y-1">
          <SettingToggle
            title="Enable Certificates"
            description="Allow the platform to issue completion certificates."
            enabled={enabled}
            onChange={() => setEnabled(!enabled)}
          />

          <SettingToggle
            title="Auto Issue Certificates"
            description="Automatically generate certificates after course completion."
            enabled={autoIssue}
            onChange={() => setAutoIssue(!autoIssue)}
          />

          <SettingToggle
            title="Require 100% Completion"
            description="Students must complete every lesson before receiving a certificate."
            enabled={requireCompletion}
            onChange={() => setRequireCompletion(!requireCompletion)}
          />

          <SettingToggle
            title="Show Instructor"
            description="Include the instructor name on certificates."
            enabled={includeInstructor}
            onChange={() => setIncludeInstructor(!includeInstructor)}
          />

          <SettingToggle
            title="Certificate ID"
            description="Add a unique verification ID to every certificate."
            enabled={includeId}
            onChange={() => setIncludeId(!includeId)}
          />
        </div>
      </SettingsCard>

      <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-5">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-indigo-600">
            <Award size={18} />
          </div>

          <div>
            <h3 className="text-sm font-extrabold text-slate-900">
              Certificate verification
            </h3>

            <p className="mt-1 text-xs leading-5 text-slate-500">
              Students can verify certificates using the unique certificate ID
              generated by the platform.
            </p>
          </div>
        </div>
      </div>
    </SettingsPage>
  );
}
